### ISSUE TITLE
`area` field in `department`, `region` and `city` has a string type instead of `float` type

### ISSUE THREAD

**Issue by loco-philippe** [MTES-MCT/qualicharge#176]
Query without cast has no result.
```
SELECT 
        SUM(city.area::float) AS total
FROM
    city
```

Note : The `area`field of `epci` is correct (float)

**Comment by jmaupetit** [comment]
This has been validated using:

```sql
SELECT
  table_name,
  column_name,
  data_type
FROM
  information_schema.columns
WHERE
  table_name IN ('city', 'department', 'epci', 'region')
  AND column_name = 'area'
```

Which gives:

| table_name | column_name | data_type        |
| ---------- | ----------- | ---------------- |
| epci       | area        | double precision |
| city       | area        | text             |
| department | area        | text             |
| region     | area        | text             |
