### ISSUE TITLE
department.population field is not equal to the sum of city.population of the department

### ISSUE THREAD

**Issue by loco-philippe** [MTES-MCT/qualicharge#177]
This gap is only with `75` and `13` department.

**Comment by jmaupetit** [comment]
This has been checked using:

```sql
SELECT
  department.code,
  department.population,
  SUM(city.population) AS cities_sum
FROM
  department
  INNER JOIN city ON department.id = city.department_id
GROUP BY
  department.code,
  department.population
HAVING
  department.population != SUM(city.population)
```

Giving:

| code | population | cities_sum |
| ---- | ---------- | ---------- |
|   69 |  1,883,177 |  2,405,427 |
|   75 |  2,133,111 |  4,266,222 |
|   13 |  2,056,943 |  2,930,019 |

**Comment by jmaupetit** [comment]
After digging a bit, it appears that for cities with "arrondissements" (Paris, Lyon, Marseille), we have the total population **and detailed population by "arrondissement"**. To avoid observed discrepancies in populations (whole department vs sum by cities), we should ignore city entries concerning "arrondissements".

Proof:

```sql
SELECT
  department.code,
  SUM(city.population)
FROM
  department
  INNER JOIN city ON department.id = city.department_id
WHERE
  city.name LIKE '%Arrondissement'
GROUP BY
  department.code
```

Result:

| code | arrondissements_population |
| ---- | -------------------------- |
|   13 |                    873,076 |
|   69 |                    522,250 |
|   75 |                  2,133,111 |

**Comment by jmaupetit** [comment]
Closing this tho.
